In [123]:
class Books:
    def __init__(self, book_name, book_cate, price):
        self.book_name = book_name
        self.book_cate = book_cate
        self.price = price

In [358]:
def Add_book():
    bk_name = name.get()
    bk_cate = cate_chosen.get()
    bk_price = price.get()
    name_lst = []
    if bk_name == "" or bk_cate =="" or bk_price =="":
        messagebox.showerror("Error!", "Please Enter name, cate and price!")
    else:
        query = 'INSERT INTO `book` (`book_name`, `category`, `price`) VALUES (%s, %s, %s);'        
        values = (bk_name, bk_cate, bk_price)
        add_query = mydb.cursor()
        add_query.execute(query,values)
        mydb.commit()
        show_query = 'SELECT * FROM book'
        query_1 = mydb.cursor()
        query_1.execute(show_query)
        rows = query_1.fetchall()
        name.delete(0,"end")
        cate_chosen.current(0)
        price.delete(0,"end")
        for i in rows:
            tree.insert('','end',iid=i[0], value = i)
        
        
def Del_book():
    selected = tree.selection()[0]
    query = 'DELETE FROM book WHERE book_name = %s'
    data = (selected,)
    delete_query = mydb.cursor()
    delete_query.execute(query,data)
    mydb.commit()
    tree.delete(selected)

def Search_book():
    search_bk_name = search_name.get()
    selected = tree.selection()[0]
    query = "SELECT FROM book WHERE book_name = %s"
    data = (selected,)
    search_query = mydb.cursor()
    search_query.execute(query,data)
    name.insert(0,selected.book_name)
    cate_chosen.insert(0, selected.book_cate)
    price.insert(0, selected.price)
                
def Update_book():
    new_price = price.get()
    selected = tree.selection()[0]
    query = 'UPDATE FROM book WHERE price = %s'
    data = (selected,)
    update_query = mydb.cursor()
    update_query.execute(query,data)
    mydb.commit()
    tree.insert(selected)
    
    Search_book().price = int(new_price)
    for i, item in enumerate(book_lst):
         tree.insert("", i, text="", values=(item.book_name, item.book_cate, item.price))
    for i in range (len(book_lst)):print(book_lst[i])

In [ ]:
import tkinter as tk
from tkinter import messagebox
from tkinter import ttk
import mysql.connector
from tkinter import *


mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="duyphan18",
  database = "demo1"
)
cursor = mydb.cursor()

show_query = 'SELECT * FROM book'
query_1 = mydb.cursor()
query_1.execute(show_query)
rows = query_1.fetchall()


app = tk.Tk()
app.title("Book Store Managent")
app.geometry("800x600")
book_lst = []

file = open("demo.txt", "a")

#Label
lbl_name = Label(app, text = "Book Name")
lbl_cate = Label(app, text = "Book Category")
lbl_price = Label(app, text = "Price")

#Input
name = Entry(app, width=30)

n = tk.StringVar()
cate_chosen = ttk.Combobox(app, width = 27, textvariable = n)
  
# Adding combobox drop down list
cate_chosen['values'] = (' Textbook ', 
                          ' Comic',
                          ' Poem',
                          ' Thriller book',
                          ' Dictionary ',
                          ' Cookery book ',
                          ' Science fiction book',
                          ' Reference book',
                          ' Novel ',
                          ' Encyclopedia ',
                          ' Myth',
                          ' Ghost story')
  
price = Entry(app, width=30)
search_name = Entry(app, width=50)

#Button"
btn_add = Button(app, text ="ADD NEW", bd=0, bg="#6296b7", justify=LEFT, height = 2, width = 10, command = Add_book)
btn_del = Button(app, text ="DELETE", bd=0, bg="#ea6a64", justify=LEFT, height = 2, width = 10, command = Del_book)
btn_update = Button(app, text ="UPDATE", bd=0, bg="#c4c4c4", justify=LEFT, height = 2, width = 10, state = DISABLED, command = Update_book)
btn_search = Button(app, text ="SEARCH", bd=0, bg="#009900", height = 1, width = 10, command = Search_book )
#treeview
columns = ('book_name', 'book_cate', 'price')
tree = ttk.Treeview(app, columns=columns, show='headings')
# define headings
tree.heading('book_name', text='Book Name')
tree.heading('book_cate', text='Category')
tree.heading('price', text='Price')

#load db into treeview
for i in rows:
    tree.insert('','end',iid=i[0], value = i)
for i in range(1, 4):
    tree.column("#"+str(i), anchor=tk.CENTER)
#Place widget
lbl_name.place(x = 100, y = 50)
name.place(x = 200, y = 50)
lbl_cate.place(x = 100, y = 100)
cate_chosen.place(x =200, y = 100)
cate_chosen.current(0)
lbl_price.place(x = 100, y = 150)
price.place(x = 200, y = 150)

search_name.place(x = 100, y = 220)
btn_search.place(x = 400, y = 220)

btn_add.place(x = 620, y = 50)
btn_del.place(x = 620, y = 100)
btn_update.place(x = 620, y = 150)
tree.place(x=100, y=250)



app.mainloop()

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\duyph\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\duyph\AppData\Local\Temp\ipykernel_4016\3352560343.py", line 22, in Add_book
    tree.insert('','end',iid=i[0], value = i)
  File "C:\Users\duyph\AppData\Local\Programs\Python\Python311\Lib\tkinter\ttk.py", line 1336, in insert
    res = self.tk.call(self._w, "insert", parent, index,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Item Conan already exists