In [1]:
class Books:
    def __init__(self, book_name, book_cate, price):
        self.book_name = book_name
        self.book_cate = book_cate
        self.price = price

In [47]:
def clear():
    name.delete(0, "end")
    cate_chosen.current()
    price.delete(0, "end")
    search_name.delete(0, "end")
    
def update(rows):
    tree.delete(*tree.get_children())
    for i in rows:
            tree.insert('','end',iid=i[0], value = i)
        
def Add_book():
    bk_name = name.get()
    bk_cate = cate_chosen.get()
    bk_price = price.get()
    name_lst = []
    if bk_name == "" or bk_cate =="" or bk_price =="":
        messagebox.showerror("Error!", "Please Enter name, cate and price!")
    else:
        query = 'INSERT INTO `book` (`book_name`, `category`, `price`) VALUES (?, ?, ?);'        
        values = (bk_name, bk_cate, bk_price)
        cursor = mydb.cursor()
        cursor.execute(query,values)
        mydb.commit()
        query = "SELECT * FROM book"
        search_query = mydb.cursor()
        search_query.execute(query)
        rows = search_query.fetchall()
        update(rows)
        clear()
        
        
        
def Del_book():
    if messagebox.askyesno("Confirm?", "Are you sure?"):
        selected = tree.selection()[0]
        query = 'DELETE FROM book WHERE book_name = ?'
        values = (selected,)
        print(values)
        cursor = mydb.cursor()
        cursor.execute(query,values)
        mydb.commit()
        query = "SELECT * FROM book"
        cursor = mydb.cursor()
        cursor.execute(query)
        rows = cursor.fetchall()
        update(rows)
    else:
        return True

def Search_book():
    search_bk_name = search_name.get()
    query = "SELECT * FROM book WHERE book_name LIKE '%"+search_bk_name+"%'"
    cursor = mydb.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    update(rows)
def Show_all():
    query = "SELECT * FROM book"
    cursor = mydb.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    update(rows)
    clear()
def Show_book():
    item = tree.item(tree.focus())
    name.insert(0,item['values'][0])
    cate_chosen.insert(0,item['values'][1])
    price.insert(0,item['values'][2])
    btn_update.config(state = ACTIVE)

def Update_book():
    bk_name =name.get()
    new_price = price.get()
    query = 'UPDATE book SET price = ? WHERE book_name = ?'
    cursor = mydb.cursor()
    cursor.execute(query,(new_price, bk_name))
    mydb.commit()
    query = "SELECT * FROM book"
    cursor = mydb.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    update(rows)
    clear()
    Show_all()

In [48]:
import tkinter as tk
from tkinter import messagebox
from tkinter import ttk
import mysql.connector
from tkinter import *
import sqlite3


# mydb = mysql.connector.connect(
#   host="localhost",
#   user="root",
#   password="duyphan18",
#   database = "demo1"
# )
# cursor = mydb.cursor()
mydb = sqlite3.connect('test.db')
a = 'CREATE TABLE IF NOT EXISTS book (book_name VARCHAR, category VARCHAR, price INT)'
cursor = mydb.cursor()
mydb.execute(a)


app = tk.Tk()
app.title("Book Store Managent")
app.geometry("800x600")
book_lst = []

file = open("demo.txt", "a")

#Label
lbl_name = Label(app, text = "Book Name")
lbl_cate = Label(app, text = "Book Category")
lbl_price = Label(app, text = "Price")

#Input
name = Entry(app, width=30)

n = tk.StringVar()
cate_chosen = ttk.Combobox(app, width = 27, textvariable = n)
  
# Adding combobox drop down list
cate_chosen['values'] = (' Textbook ', 
                          ' Comic',
                          ' Poem',
                          ' Thriller book',
                          ' Dictionary ',
                          ' Cookery book ',
                          ' Science fiction book',
                          ' Reference book',
                          ' Novel ',
                          ' Encyclopedia ',
                          ' Myth',
                          ' Ghost story')
  
price = Entry(app, width=30)
search_name = Entry(app, width=50)

#Button"
btn_add = Button(app, 
                 text ="ADD NEW", 
                 bd=0, bg="#6296b7", 
                 justify=LEFT, 
                 height = 2, width = 10, 
                 command = Add_book)
btn_show = Button(app, 
                 text ="SHOW", 
                 bd=0, bg="#ea6a64", 
                 justify=LEFT, 
                 height = 2, width = 10, 
                 command = Show_book)
btn_del = Button(app, 
                 text ="DELETE", 
                 bd=0, bg="#ea6a64", 
                 justify=LEFT, 
                 height = 2, width = 10, 
                 command = Del_book)
btn_update = Button(app, 
                    text ="UPDATE", 
                    bd=0, bg="#c4c4c4", 
                    justify=LEFT, 
                    height = 2, width = 10, 
                    state = DISABLED, 
                    command = Update_book)
btn_search = Button(app, 
                    text ="SEARCH", 
                    bd=0, bg="#009900", 
                    height = 1, width = 10, 
                    command = Search_book )
btn_showall = Button(app, 
                    text ="ALL", 
                    bd=0, bg="#009900", 
                    height = 1, width = 10, 
                    command = Show_all )
#treeview
columns = ('book_name', 'book_cate', 'price')
tree = ttk.Treeview(app, columns=columns, show='headings')
# define headings
tree.heading('book_name', text='Book Name')
tree.heading('book_cate', text='Category')
tree.heading('price', text='Price')
#load db into treeview
show_query = 'SELECT * FROM book'
cursor.execute(show_query)
rows = cursor.fetchall()
for i in rows:
    tree.insert('','end',iid=i[0], value = i)
for i in range(1, 4):
    tree.column("#"+str(i), anchor=tk.CENTER)
#Place widget
lbl_name.place(x = 100, y = 50)
name.place(x = 200, y = 50)
lbl_cate.place(x = 100, y = 100)
cate_chosen.place(x =200, y = 100)
cate_chosen.current()
lbl_price.place(x = 100, y = 150)
price.place(x = 200, y = 150)

btn_showall.place(x = 100, y = 220)
search_name.place(x = 175, y = 220)
btn_search.place(x = 480, y = 220)

btn_add.place(x = 620, y = 50)
btn_del.place(x = 620, y = 100)
btn_update.place(x = 620, y = 150)
btn_show.place(x=620, y = 200)
tree.place(x=100, y=250)



app.mainloop()

('mon',)